### ISSUE TITLE
git init bug?

### ISSUE THREAD

**Issue by lanthree** [oh-my-fish/theme-chain#9]
Open terminal like iterm2.
Run `git init` before `cd` any git workdir.
Problem just happen:
![image](https://user-images.githubusercontent.com/4102576/58377200-69a4f980-7fad-11e9-8f08-9b4017e5385b.png)

I guess the cause is: `vcs.present` refresh before `vcs.root`, and `vcs.refresh` and `chain.links.pwd.fish` are not run in order.

So, I just modify `chain.links.pwd.fish` like this:
```fish chain.links.pwd.fish
[12:01:30]-[@theme-chain/functions]-[⎇ master]-[±]-> git diff
diff --git a/functions/chain.links.pwd.fish b/functions/chain.links.pwd.fish
index 1cb078c..dfaafe6 100644
--- a/functions/chain.links.pwd.fish
+++ b/functions/chain.links.pwd.fish
@@ -6,7 +6,7 @@ function chain.links.pwd
   set -l path "$PWD"

   # Replace either HOME with ~ or abbreviate project root.
-  if vcs.present
+  if vcs.refresh && vcs.present
     set path (string replace (vcs.root) '' "$path")
     set prefix @(basename (vcs.root))
   else
[12:01:32]-[@theme-chain/functions]-[⎇ master]-[±]->
```

Then, the problem is fixed!
![image](https://user-images.githubusercontent.com/4102576/58377247-a0c7da80-7fae-11e9-8c66-f461ab8f9c3d.png)

**Comment by sagebind** [comment]
Indeed this looks like a bug. Want to open your patch as a pull request?
